from herernça_ex_01 import personagem

Kamilinha = personagem(1.48 , 'castanho escuro', 'Kamilinha', 'Feminista', 'Pirulito', 'Triste', 'Felca')
Virginia_Fonseca = personagem(1.70 , 'azuis', 'Virginia', 'F', 'Sushi', 'Triste', 'Zé Felipe')
Zé_felipe = personagem(1.80 , 'castanho claro', 'Zé felipe', 'M', 'Churrasco', 'Apaixonado', 'Virginia')
Davi_Brito = personagem(1.75 , 'castanho escuro', 'Davi Brito', 'M', 'Picanha', 'Solteiro', 'Bia do Bras')
Bia_do_bras = personagem(1.48 , 'castanho claro', 'Beatris Reis', 'F', 'Comer no bras', 'Solteira', 'Davi Brito')

print("-"*50)
Kamilinha.vida()
Kamilinha.comida()
Kamilinha.papai_hytalo()
Kamilinha.chato()
Kamilinha.eyes()
print("-"*50)
Virginia_Fonseca.chato()
print("-"*50)
Zé_felipe.chato()
Zé_felipe.comida()
print("-"*50)
Davi_Brito.chato()
Davi_Brito.vida()
print("-"*50)
Bia_do_bras.vida()
Bia_do_bras.eyes()
Bia_do_bras.comida()
print("-"*50)
